using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Text;

namespace Matrix.SurveyServer.Driver.Erz2000
{
    public partial class Driver
    {
        private dynamic GetAbnormal(byte na, int number)
        {
            dynamic abnormal = new ExpandoObject();
            abnormal.success = true;

            abnormal.records = new List<dynamic>();

            var h = ParseRecord(Send(MakeRecordRequest(na, 20, 1, number)));
            if (!h.success) return h;
            abnormal.date = h.date;
            abnormal.number = h.number;

            var h1 = ParseRecord(Send(MakeRecordRequest(na, 20, 2, number)));
            if (!h1.success) return h1;

            var h2 = ParseRecord(Send(MakeRecordRequest(na, 20, 3, number)));
            if (!h2.success) return h2;

            var h3 = ParseRecord(Send(MakeRecordRequest(na, 20, 13, number)));
            if (!h3.success) return h3;

            var h4 = ParseRecord(Send(MakeRecordRequest(na, 20, 12, number)));
            if (!h4.success) return h4;

            var msg = string.Format("{0} (P={1}; T={2}, Qn={3}, Qw={4})", GetAbnormalMessage((int)h.value),h1.value, h2.value, h3.value, h4.value);
            log(msg);
            abnormal.records.Add(MakeAbnormalRecord(msg, 0, h.date));

            return abnormal;
        }

        private string GetAbnormalMessage(int code)
        {
            switch (code)
            {
                case 0: return "(T сбой) Исчезновение сигнала температуры";
                case 1: return "(T < сиг. трев.-GWU) Температура меньше нижней границы тревоги";
                case 2: return "(T > сиг. трев.-GWO) Температура выше верхней границы тревоги";
                case 3: return "(T-скачок) Градиент температуры больше допустимого";
                case 4: return "T < предупр.-GWU";
                case 5: return "T > предупр.-GWO";
                case 6: return "T ошибка парам.";
                case 7: return "(TS сбой) Исчезновение сигнала температуры VOS";
                case 8: return "(TS < сиг. трев.-GWU) Температура VOS меньше нижней границы тревоги";
                case 9: return "(TS > сиг. трев.-GWO) Температура VOS выше верхней границы тревоги";
                case 10: return "(TS-скачок) Градиент VOS- температуры больше допустимого";
                case 11: return "TS < предупр.-GWU";
                case 12: return "TS > предупр.-GWO";
                case 13: return "TS ошибка парам.";
                case 14: return "(TD сбой) Исчезновение сигнала температуры датчика плотности";
                case 15: return "(TD < сиг. трев.-GWU) Температура датчика плотности меньше нижней границы тревоги";
                case 16: return "(TD > сиг. трев.-GWO) Температура датчика плотности выше верхней границы тревоги";
                case 17: return "(TD-скачок) Градиент температуры датчика плотности больше допустимого";
                case 18: return "TD < предупр.-GWU";
                case 19: return "TD > предупр.-GWO";
                case 20: return "TD ошибка парам.";
                case 21: return "(Pa сбой) Исчезновение сигнала абсолютного давления";
                case 22: return "(Pa < сиг. трев.-GWU) Абсолютное давление меньше нижней границы тревоги";
                case 23: return "(Pa > сиг. трев.-GWO) Абсолютное давление выше верхней границы тревоги";
                case 24: return "(Pa-скачок) Градиент абсолютного давления больше допустимого";
                case 25: return "Pa < предупр.-GWU";
                case 26: return "Pa > предупр.-GWO";
                case 27: return "Pa ошибка парам.";
                case 28: return "(Rn сбой) Исчезновение сигнала нормальной плотности";
                case 29: return "(Rn < сиг. трев.-GWU) Нормальная плотность меньше нижней границы тревоги";
                case 30: return "(Rn > сиг. трев.-GWO) Нормальная плотность выше верхней границы тревоги";
                case 31: return "(Rn - скачок) Градиент нормальной плотности больше допустимого";
                case 32: return "Rn < предупр.-GWU";
                case 33: return "Rn > предупр.-GWO";
                case 34: return "Vo предупреждение";
                case 35: return "(HW - импульс. сравнен.) Сбой сравнения аппаратных импульсов";
                case 36: return "синхронность";
                case 37: return "Rn ошибка парам.";
                case 38: return "(Rb сбой) Исчезновение сигнала рабочей плотности";
                case 39: return "(Rb < сиг. трев.-GWU) Рабочая плотность меньше нижней границы тревоги";
                case 40: return "(Rb > сиг. трев.-GWO passiv) Рабочая плотность выше верхней границы тревоги";
                case 41: return "(Rb - скачок) Градиент рабочей плотности больше допустимого";
                case 42: return "Rb < предупр.-GWU";
                case 43: return "Rb > предупр.-GWO passiv";
                case 44: return "(Rb - ошибка вычисл) Ошибочный расчет рабочей плотности";
                case 45: return "Имп. аккум.>макс..";
                case 46: return "(Vo сигнал тревоги) Vo исчезновение сигнала действия ошибки тревоги";
                case 47: return "Rb ошибка парам.";
                case 48: return "(Ho сбой) Исчезновение сигнала теплотворной способности";
                case 49: return "(Ho < сиг. трев.-GWU) Теплотворная способность меньше нижней границы тревоги";
                case 50: return "(Ho > сиг. трев.-GWO) Теплотворная способность выше верхней границы тревоги";
                case 51: return "(Ho - скачок) Градиент теплотворной способности больше допустимого";
                case 52: return "Ho < предупр.-GWU";
                case 53: return "Ho > предупр.-GWO";
                case 54: return "Ho ошибка парам.";
                case 55: return "(CO2 сбой) Исчезновение сигнала CO2";
                case 56: return "(CO2 < сиг. трев.-GWU) CO2 меньше нижней границы тревоги";
                case 57: return "(CO2 > сиг. трев.-GWO) CO2 выше верхней границы тревоги";
                case 58: return "(CO2 - скачок) Градиент CO2 больше допустимого";
                case 59: return "CO2 < предупр.-GWU";
                case 60: return "CO2 > предупр.-GWO";
                case 61: return "CO2 ошибка парам.";
                case 62: return "(VSB сбой) Исчезновение сигнала рабочего VOS";
                case 63: return "(VSB < сиг. трев.-GWU) Рабочий VOS меньше нижней границы тревоги";
                case 64: return "(VSB > сиг. трев.-GWO) Рабочий-VOS выше верхней границы тревоги";
                case 65: return "(VSB - скачок) Градиент рабочего VOS больше допустимого";
                case 66: return "VSB < предупр.-GWU";
                case 67: return "VSB > предупр.-GWO";
                case 68: return "VSB ошибка парам.";
                case 69: return "(H2 сбой) Исчезновение сигнала водорода";
                case 70: return "(H2 < сиг. трев.-GWU) Водород меньше нижней границы тревоги";
                case 71: return "(H2 > сиг. трев.-GWO) Водород выше верхней границы тревоги";
                case 72: return "(H2 - скачок) Градиент водорода больше допустимого";
                case 73: return "H2 < предупр.-GWU";
                case 74: return "H2 > предупр.-GWO";
                case 75: return "H2 ошибка парам.";
                case 76: return "синхрон.канал1";
                case 77: return "синхрон.канал2";
                case 78: return "разгон>макс. время";
                case 79: return "движ по ин.>макс. время";
                case 80: return "(VSN сбой) Исчезновение сигнала нормального VOS";
                case 81: return "(VSN < сиг. трев.-GWU) Нормальный VOS меньше нижней границы тревоги";
                case 82: return "(VSN > сиг. трев.-GWO) Нормальный-VOS выше верхней границы тревоги";
                case 83: return "(VSN - скачок) Градиент нормального VOS больше допустимого";
                case 84: return "VSN < предупр.-GWU";
                case 85: return "VSN > предупр.-GWO";
                case 86: return "VSN ошибка парам.";
                case 87: return "(Pu сбой) Исчезновение сигнала избыточного давления";
                case 88: return "(Pu<сиг. трев.-GWU) Избыточное давление меньше нижней границы тревоги";
                case 89: return "(Pu>сиг. трев.-GWO) Избыточное давление выше верхней границы тревоги";
                case 90: return "(Pu-скачок) Градиент избыточного давления больше допустимого";
                case 91: return "Pu<предупр.-GWU";
                case 92: return "Pu>предупр.-GWO";
                case 93: return "Pu ошибка парам.";
                case 94: return "(N2 сбой) Исчезновение сигнала азота";
                case 95: return "(N2<сиг. трев.-GWU) Азот меньше нижней границы тревоги";
                case 96: return "(N2>сиг. трев.-GWO) Азот выше верхней границы тревоги";
                case 97: return "(N2-скачок) Градиент азота больше допустимого";
                case 98: return "N2<предупр.-GWU";
                case 99: return "N2>предупр.-GWO";
                case 100: return "N2 ошибка парам.";
                case 101: return "ошибка мalloc";
                case 102: return "CAN ошибка";
                case 103: return "CAN избыток";
                case 104: return "AM сбой";
                case 105: return "(CRC12-ошибка) Нарушено требование обязательной поверки данных GC";
                case 106: return "GC-Syntax";
                case 107: return "(GC-Komm.";
                case 108: return "новый пуск passiv";
                case 109: return "(RTC дефектен) Часы реального времени дефектны";
                case 110: return "(счетный мех-м дефек.) Дефект счетного механизма";
                case 111: return "I1-вход. парам.";
                case 112: return "I2-вход. парам.";
                case 113: return "I3-вход. парам.";
                case 114: return "I4-вход. парам.";
                case 115: return "I5-вход. парам.";
                case 116: return "I6-вход. парам.";
                case 117: return "PT1-вход. парам.";
                case 118: return "PT2-вход. парам.";
                case 119: return "(T<>GERG-Gr) Температура за пределами GERG-границ";
                case 120: return "(P<>GERG-Gr) Давление за пределами GERG-границ ";
                case 121: return "(Dv<>GERG-Gr) Относительная плотность за пределами GERG-границ";
                case 122: return "(CO2<>GERG-Gr) CO2 за пределами GERG-границ";
                case 123: return "(N2<>GERG-Gr) Азот за пределами GERG-границ";
                case 124: return "(Ho<>GERG-Gr) Теплотворная способность за пределами GERG-границ";
                case 125: return "(H2<>GERG-Gr) Водород за пределами GERG-границ";
                case 126: return "(GERG-IterMax) Максимально допустимые GERG-итерации превышены";
                case 127: return "(T<>AGA-граница) Температура за пределами AGA-границ";
                case 128: return "(P<>AGA-граница) Давление за пределами AGA-границ";
                case 129: return "(Dv<>AGA-граница) Относительная плотность за пределами AGA-границ";
                case 130: return "(CO2<>AGA-граница) CO2 за пределами AGA-границ";
                case 131: return "(N2<>AGA-граница) Азот за пределами AGA-границ";
                case 132: return "(Ho<>AGA-граница) Теплотворная способность за пределами AGA-границ";
                case 133: return "(H2<>AGA-граница) Водород за пределами AGA-границ";
                case 134: return "(AGA алгоритм) Ошибка алгоритма AGANX, паника";
                case 135: return "(AGA-Pi, роса) AGA-промежуточные результаты Pi,Tau за пределами границ";
                case 136: return "(Проблема опор. точки) Ошибка при расчете опорной точки";
                case 137: return "Q<Q-Min";
                case 138: return "Q>Q-Max";
                case 139: return "Поверочный замок";
                case 140: return "Замок пользователя";
                case 141: return "Редакция";
                case 142: return "Замен.GBH акт.";
                case 143: return "GBH1-сбой";
                case 144: return "GBH2-сбой";
                case 145: return "Rn GBH1-сбой";
                case 146: return "Rn GBH2-сбой";
                case 147: return "Ho GBH1-сбой";
                case 148: return "Ho GBH2-сбой";
                case 149: return "CO2 GBH1-сбой";
                case 150: return "CO2 GBH2-сбой";
                case 151: return "H2 GBH1-сбой";
                case 152: return "H2 GBH2-сбой";
                case 153: return "N2 GBH1-сбой";
                case 154: return "N2 GBH2-сбой";
                case 155: return "VSB<>теория";
                case 156: return "Отсутст. часовой ритм";
                case 157: return "(Dv GBH1-сбой) Исчезновение сигнала расхода, пропорционального по току";
                case 158: return "Dv GBH2-сбой";
                case 159: return "(канал 1 ошибка) Недостоверный подсчет импульсов канала 1";
                case 160: return "(канал 2 ошибка) Недостоверный подсчет импульсов канала 2";
                case 161: return "(TB/TN-Kombi.) Недопустимая комбинация TB/TN";
                case 162: return "CAN контроль";
                case 163: return "Сервисный запрос";
                case 164: return "Старое время";
                case 165: return "Новое время";
                case 166: return "Сеть выкл. пассив";
                case 167: return "импульс 1 >макс.";
                case 168: return "импульс 2 >макс.";
                case 169: return "импульс 3 >макс.";
                case 170: return "импульс 4 >макс.";
                case 171: return "I1-вых.<мин";
                case 172: return "I2-вых.<мин";
                case 173: return "I3-вых.<мин";
                case 174: return "I4-вых.<мин";
                case 175: return "I1-вых.>макс.";
                case 176: return "I2-вых.>макс.";
                case 177: return "I3-вых.>макс.";
                case 178: return "I4-вых.>макс.";
                case 179: return "I1-вых. парам.";
                case 180: return "I2-вых. парам.";
                case 181: return "I3-вых. парам.";
                case 182: return "I4-вых. парам.";
                case 183: return "K1-вых. парам.";
                case 184: return "K2-вых. парам.";
                case 185: return "K3-вых. парам.";
                case 186: return "K4-вых. парам.";
                case 187: return "K5-вых. парам.";
                case 188: return "K6-вых. парам.";
                case 189: return "K7-вых. парам.";
                case 190: return "K8-вых. парам.";
                case 191: return "t>Rn-время корр.";
                case 192: return "RnKorr сигнал";
                case 193: return "RnKorr>доп.(W)";
                case 194: return "t>Ho-время корр.";
                case 195: return "HoKorr сигнал";
                case 196: return "HoKorr>доп.(W)";
                case 197: return "(dkvk>макс.) Максимальное отклонение в рабочей точке превышено";
                case 198: return "F1 сбой";
                case 199: return "F2 сбой";
                case 200: return "I1 сбой";
                case 201: return "I2 сбой";
                case 202: return "I3 сбой";
                case 203: return "I4 сбой";
                case 204: return "I5 сбой";
                case 205: return "I6 сбой";
                case 206: return "PT1 сбой";
                case 207: return "PT2 сбой";
                case 208: return "Ktk-вход дефектный";
                case 209: return "HoKorr>доп.(H)";
                case 210: return "RnKorr>доп.(H)";
                case 211: return "(Матем. проблема) Математическая ошибка";
                case 212: return "(Dv сбой) Исчезновение сигнала относительной плотности";
                case 213: return "(Dv<сиг. трев.-GWU) Относительная плотность меньше нижней границы тревоги";
                case 214: return "(Dv>сиг. трев.-GWO) Относительная плотность выше верхней границы тревоги";
                case 215: return "(Dv-скачок) Градиент относительной плотности больше допустимого";
                case 216: return "Dv<предупр.-GWU";
                case 217: return "Dv>предупр.-GWO";
                case 218: return "Dv ошибка парам.";
                case 219: return "(Ho GC-тайм-аут) Датчик теплотворной способности более не передает данные";
                case 220: return "(Rn GC-тайм-аут) Датчик нормальной плотности более не передает данные";
                case 221: return "(Dv GC-тайм-аут) Датчик относительной плотности более не передает данные";
                case 222: return "(CO2 GC-тайм-аут) Датчик СО2 более не передает данные";
                case 223: return "(N2 GC-тайм-аут) Датчик N2 более не передает данные";
                case 224: return "(H2 GC-тайм-аут) Датчик Н2 более не передает данные";
                case 225: return "(Ho GC-сигнал тревоги) GC сигнализирует об исчезновении сигнала теплотворной способности";
                case 226: return "(Rn GC-сигнал тревоги) GC сигнализирует об исчезновении сигнала норм. плотности";
                case 227: return "(Dv GC-сигнал тревоги) GC сигнализирует об исчезновении сигнала относительной плотности";
                case 228: return "(CO2 GC-сигнал трев.) GC сигнализирует об исчезновении сигнала CO2";
                case 229: return "(N2 GC-сигнал тревоги) GC сигнализирует об исчезновении сигнала азота";
                case 230: return "(H2 GC-сигнал тревоги) GC сигнализирует об исчезновении сигнала водорода";
                case 231: return "(Beattie сигнал тревоги) итерация Beattie+Bridgeman выдает ложные результаты";
                case 232: return "(CH4 сбой) Исчезновение сигнала метана";
                case 233: return "(CH4<сиг. трев.-GWU) Метан меньше нижней границы тревоги";
                case 234: return "(CH4>сиг. трев.-GWO) Метан выше верхней границы тревоги";
                case 235: return "(CH4-скачок) Градиент метана больше допустимого";
                case 236: return "CH4<предупр.-GWU";
                case 237: return "CH4>предупр.-GWO";
                case 238: return "CH4 ошибка парам.";
                case 239: return "Комп. нормиров.";
                case 240: return "Отсутствует разреш.";
                case 241: return "TCP согласно Boot";
                case 242: return "(CH4 GC-тайм-аут) Датчик метана более не передает данные";
                case 243: return "(CH4 GC-сигнал тревоги) GC сигнализирует об исчезновении сигнала метана";
                case 244: return "Float согласовано";
                case 245: return "(VOS-ошибка корр.) Ошибка при расчете корректировки VOS";
                case 246: return "(Z-число сравнение) Отсутствует первичное значение для расчета коэффициента состояния";
                case 247: return "(AGA8 сигнал тревоги) AGA 8 ошибка алгоритма";
                case 248: return "(AGA8 92DC сигнал тр.) AGA 8 92DC ошибка алгоритма";
                case 249: return "композ.<>AGA 8";
                case 250: return "I7-вход. парам.";
                case 251: return "I8-вход. парам.";
                case 252: return "I7 сбой";
                case 253: return "I8 сбой";
                case 254: return "перегрев";
                case 255: return "переохлаждение";
                case 256: return "(v.d.Waals сигнал трев.) Бесконтрольное выполнение повторений Van der Waals";
                case 257: return "Ktk ошибка парам.";
                case 258: return "Vo дефектен";
                case 259: return "Vo тайм-аут";
                case 260: return "Vo/DZU протокол";
                case 261: return "Импульсы стерты";
                case 262: return "(GC-компоненты) плохие компоненты GC для полного анализа";
                case 263: return "индикация дефектна";
                case 264: return "рабочее испытание";
                case 265: return "DZU недостоверен";
                case 266: return "(DZU сигнал тревоги) Датчик DZU сигнализирует о тревоге";
                case 267: return "(DZU тайм-аут) Датчик DZU более не передает данные";
                case 268: return "Vo1 недостоверен";
                case 269: return "Vo2 недостоверен";
                case 270: return "SVo1 недостоверен";
                case 271: return "SVo2 недостоверен";
                case 272: return "Парам. времен. синхр.";
                case 273: return "F3 сбой";
                case 274: return "F4 сбой";
                case 275: return "(канал 3 ошибка) Недостоверный подсчет импульсов канала 3";
                case 276: return "(канал 4 ошибка) Недостоверный подсчет импульсов канала 4";
                case 277: return "HF ошибка парам.";
                case 278: return "вызов";
                case 279: return "PTB-время";
                case 280: return "Qb<предупр.-GWU";
                case 281: return "Qb>предупр.-GWO";
                case 282: return "Qk<предупр.-GWU";
                case 283: return "Qk>предупр.-GWO";
                case 284: return "Qn<предупр.-GWU";
                case 285: return "Qn>предупр.-GWO";
                case 286: return "Qe<предупр.-GWU";
                case 287: return "Qe>предупр.-GWO aktiv ";
                case 288: return "Qm<предупр.-GWU";
                case 289: return "Qm>предупр.-GWO";
                case 290: return "(CAN тайм-аут) Превышение времени шины CAN";
                case 291: return "Неисправен модем";
                case 292: return "заводское состояние";
                case 293: return "PT1 обрыв провода";
                case 294: return "PT2 обрыв провода";
                case 295: return "Z-число ошибка";
                case 296: return "Этан<предупр.-GWU";
                case 297: return "Этан>предупр.-GWO";
                case 298: return "Пропан<предупр.GWU";
                case 299: return "Пропан>предупр.GWO";
                case 300: return "N-бут.<предупр.-GWU";
                case 301: return "N-бут.>предупр.-GWO";
                case 302: return "I-бут.<предупр.-GWU";
                case 303: return "I-бут.>предупр.-GWO";
                case 304: return "N-пент.<предупр.GWU";
                case 305: return "N-пент.>предупр.GWO";
                case 306: return "I-пент.<предупр.GWU";
                case 307: return "I-пент.>предупр.GWO";
                case 308: return "Нео-п.<предупр.-GWU";
                case 309: return "Нео-п.>предупр.-GWO";
                case 310: return "Гексан<предупр.-GWU";
                case 311: return "Гексан>предупр.-GWO";
                case 312: return "Гептан<предупр.GWU";
                case 313: return "Гептан>предупр.GWO";
                case 314: return "Октан<предупр.-GWU";
                case 315: return "Октан>предупр.-GWO";
                case 316: return "Нонан<предупр.-GWU";
                case 317: return "Нонан>предупр.-GWO";
                case 318: return "Декан<предупр.-GWU";
                case 319: return "Декан>предупр.-GWO";
                case 320: return "H2S<предупр.-GWU";
                case 321: return "H2S>предупр.-GWO";
                case 322: return "H2O<предупр.-GWU";
                case 323: return "H2O>предупр.-GWO";
                case 324: return "He<предупр.-GWU";
                case 325: return "He>предупр.-GWO";
                case 326: return "O2<предупр.-GWU";
                case 327: return "O2>предупр.-GWO";
                case 328: return "CO<предупр.-GWU";
                case 329: return "CO>предупр.-GWO";
                case 330: return "Этилен<предупр.-GWU";
                case 331: return "Этилен>предупр.-GWO";
                case 332: return "Пропен<предупр.GWU";
                case 333: return "Пропен>предупр.GWO";
                case 334: return "Аргон<предупр.-GWU";
                case 335: return "Аргон >предупр.-GWO";
                case 336: return "RMG-шина отсутствует";
                case 337: return "RMG шина-ошиб. пар.";
                case 338: return "DSfG-ошибка парам.";
                case 339: return "TCPIP-ошибка";
                case 340: return "Дефект ПО";
                case 341: return "Файловая система";
                case 342: return "DSfG TG-знач.";
                case 343: return "DSfG изыбток";
                case 344: return "DSfG Blockchk";
                case 345: return "DSfG Att. BCC";
                case 346: return "DSfG Att. ign.";
                case 347: return "DSfG Busterm.";
                case 348: return "F5 сбой";
                case 349: return "F6 сбой";
                case 350: return "F7 сбой";
                case 351: return "F8 сбой";
                case 352: return "HART1 сбой";
                case 353: return "HART2 сбой";
                case 354: return "HART3 сбой";
                case 355: return "HART4 сбой";
                case 356: return "HART5 сбой";
                case 357: return "HART6 сбой";
                case 358: return "Парам. испорчен";
                case 359: return "Код испорчен";
                case 360: return "(Сигн. трев. объем.geb.) Подключенный контакт датчика объема подает сигнал тревоги";
                case 361: return "Предупр. объем.geb.";
                case 362: return "(IGM-замен. значение) используется недействительное заменяющее значение для IGM";
                case 363: return "(Сбой луча>доп.) Слишком большое количество отключенных лучей";
                case 364: return "AGA8<>область";
                case 365: return "(ETA сбой) Исчезновение сигнала вязкости";
                case 366: return "(ETA<сиг. трев.-GWU) Вязкость меньше нижней границы тревоги";
                case 367: return "(ETA>сиг. трев.-GWO) Вязкость выше верхней границы тревоги";
                case 368: return "ETA<предупр.-GWU";
                case 369: return "ETA>предупр.-GWO";
                case 370: return "ETA ошибка парам.";
                case 371: return "(ETA-скачок) Градиент вязкости больше допустимого";
                case 372: return "луч 1 значение измер.";
                case 373: return "луч 2 значение измер.";
                case 374: return "луч 3 значение измер.";
                case 375: return "луч 4 значение измер.";
                case 376: return "луч 5 значение измер.";
                case 377: return "луч 6 значение измер.";
                case 378: return "луч 7 значение измер.";
                case 379: return "луч 8 значение измер.";
                case 380: return "луч 1 связь";
                case 381: return "луч 2 связь";
                case 382: return "луч 3 связь";
                case 383: return "луч 4 связь";
                case 384: return "луч 5 связь";
                case 385: return "луч 6 связь";
                case 386: return "луч 7 связь";
                case 387: return "луч 8 связь";
                case 388: return "луч 1 VOS";
                case 389: return "луч 2 VOS";
                case 390: return "луч 3 VOS";
                case 391: return "луч 4 VOS";
                case 392: return "луч 5 VOS";
                case 393: return "луч 6 VOS";
                case 394: return "луч 7 VOS";
                case 395: return "луч 8 VOS";
                case 396: return "Опознаван. шины<>12";
                case 397: return "DFÜ-текущ<>16";
                case 398: return "недопустимо";
                case 399: return "Новый запуск архива";
                case 400: return "SM1 сбой";
                case 401: return "SM1<предупр.-GWU";
                case 402: return "SM1>предупр.-GWO";
                case 403: return "(Rn сбой 2EW) Исчезновение сигнала нормальной плотности, второе входное значение";
                case 404: return "SM1 сбой 2EW";
                case 405: return "все okay";
                case 406: return "msg2";
                case 407: return "msg3";
                case 408: return "msg4";
                case 409: return "все okay";
                case 410: return "msg2";
                case 411: return "msg3";
                case 412: return "msg4";
                case 413: return "все okay";
                case 414: return "msg2";
                case 415: return "msg3";
                case 416: return "msg4";
                case 417: return "SM2 сбой";
                case 418: return "SM2<предупр.-GWU";
                case 419: return "SM2>предупр.-GWO";
                case 420: return "SM2 сбой 2EW";
                case 421: return "SМ3 сбой";
                case 422: return "SМ3<предупр.-GWU";
                case 423: return "SМ3>предупр.-GWO";
                case 424: return "SМ3 сбой 2EW";
                case 425: return "SM4 сбой";
                case 426: return "SM4<предупр.-GWU";
                case 427: return "SM4>предупр.-GWO";
                case 428: return "SM4 сбой 2EW";
                case 429: return "SM5 сбой";
                case 430: return "SM5<предупр.-GWU";
                case 431: return "SM5>предупр.-GWO";
                case 432: return "SM5 сбой 2EW";
                case 433: return "SM6 сбой";
                case 434: return "SM6<предупр.-GWU";
                case 435: return "SM6>предупр.-GWO";
                case 436: return "SM6 сбой 2EW";
                case 437: return "SM7 сбой";
                case 438: return "SM7<предупр.-GWU";
                case 439: return "SM7>предупр.-GWO";
                case 440: return "SM7 сбой 2EW";
                case 441: return "SM8 сбой";
                case 442: return "SM8<предупр.-GWU";
                case 443: return "SM8>предупр.-GWO";
                case 444: return "SM8 сбой 2EW";
                case 445: return "Игнорир. парам.";
                case 446: return "msg5";
                case 447: return "msg6";
                case 448: return "msg7";
                case 449: return "msg8";
                case 450: return "msg5";
                case 451: return "msg6";
                case 452: return "msg7";
                case 453: return "msg8";
                case 454: return "msg5";
                case 455: return "msg6";
                case 456: return "msg7";
                case 457: return "msg8";
                case 458: return "LCD тип/язык";
                case 459: return "Времен. синхр. игнор.";
                case 460: return "Временная ошибка сети";
                case 461: return "HART9 сбой";
                case 462: return "HART10 сбой";
                case 463: return "HART11 сбой";
                case 464: return "HART12 сбой";
                case 465: return "I9-вход. парам.";
                case 466: return "I10-вход. парам.";
                case 467: return "I11-вход. парам.";
                case 468: return "I12-вход. парам.";
                case 469: return "I9 сбой";
                case 470: return "I10 сбой";
                case 471: return "I11 сбой";
                case 472: return "I12 сбой";
                case 473: return "PT3-вход. парам.";
                case 474: return "PT4-вход. парам.";
                case 475: return "PT3 сбой";
                case 476: return "PT4 сбой";
                case 477: return "(NMA ADC) Namur модуль A аналоговый преобразователь";
                case 478: return "(NMA перегрузка) Namur модуль A перегрузка";
                case 479: return "(NMA Lb PT100) Namur модуль A обрыв провода PT100";
                case 480: return "(NMA Lb измерит. канал) Namur модуль A обрыв провода измерительного канала";
                case 481: return "(NMA Lb сравнит. канал) Namur модуль A обрыв провода канала сравнения";
                case 482: return "NMA Lb ENCO";
                case 483: return "(NMB ADC) Namur модуль В аналоговый преобразователь";
                case 484: return "(NMB перегрузка) Namur модуль В перегрузка";
                case 485: return "(NMB Lb PT100) Namur модуль В обрыв провода PT100";
                case 486: return "(NMB Lb измерит. канал) Namur модуль В обрыв провода измерительного канала";
                case 487: return "(NMB Lb сравнит. канал) Namur модуль В обрыв провода канала сравнения";
                case 488: return "NMB Lb ENCO";
                case 489: return "модуль 1A ошибочный";
                case 490: return "модуль 1B ошибочный";
                case 491: return "модуль 2A ошибочный";
                case 492: return "модуль 2B ошибочный";
                case 493: return "модуль 3A ошибочный";
                case 494: return "модуль 3B ошибочный";
                case 495: return "(Kappa сбой) Исчезновение сигнала показателя изэнтропы";
                case 496: return "(Kappa<сиг. трев.-GWU) Показатель изэнтропы меньше нижней границы тревоги";
                case 497: return "(Kappa>сиг. трев.-GWO) Показатель изэнтропы выше верхней границы тревоги";
                case 498: return "Kappa<предупр.-GWU";
                case 499: return "Kappa>предупр.-GWO";
                case 500: return "Kappa ошибка парам.";
                case 501: return "(Kappa-скачок) Градиент показателя изэнтропы больше допустимого";
                case 502: return "(JTK сбой) Коэфф. Джоуля-Томсона вязкость";
                case 503: return "(JTK<сиг. трев.-GWU) Коэфф. Джоуля-Томсона. меньше нижней границы тревоги";
                case 504: return "(JTK>сиг. трев.-GWO) Коэфф. Джоуля-Томсона. больше верхней границы тревоги";
                case 505: return "JTK<предупр.-GWU";
                case 506: return "JTK>предупр.-GWO";
                case 507: return "JTK ошибка парам.";
                case 508: return "(JTK-скачок) Градиент коэфф. Джоуля-Томсона больше допустимого";
                case 509: return "Поток при закр";
                case 510: return "(DP1 (I<3мA)) Ячейка дельта-P 1 ток меньше 3 мA";
                case 511: return "(DP2 (I<3мA)) Ячейка дельта-P 2 ток меньше 3 мA";
                case 512: return "(DP3 (I<3мA)) Ячейка дельта-P 3 ток меньше 3 мA";
                case 513: return "(Beta недопустимо) Недопустимое соотношение диафрагма/труба";
                case 514: return "(DP1 сбой) Ячейка дельта-P 1 исчезновение сигнала";
                case 515: return "(DP2 сбой) Ячейка дельта-P 2 исчезновение сигнала";
                case 516: return "(DP3 сбой) Ячейка дельта-P 3 исчезновение сигнала";
                case 517: return "(DP>макс.) Дельта-P больше допустимого";
                case 518: return "DP не соответствуют";
                case 519: return "HART-корр.>макс.";
                case 520: return "DP1K отклонен";
                case 521: return "G486 поврежден";
                case 522: return "(GQM-список) Неверный список GQM";
                case 523: return "(HGBH неизвестен) Основной GBH, неизвестная идентификация";
                case 524: return "(VGBH неизвестен) Сравнительный GBH, неизвестная идентификация";
                case 525: return "(HGBH CRC12) Основной GBH, недостоверный CRC12";
                case 526: return "(VGBH CRC12) Сравнительный GBH, недостоверный CRC12";
                case 527: return "Поток при закр.";
                case 528: return "FC-BIOS старый";
                case 529: return "HART1 состояние";
                case 530: return "HART2 состояние";
                case 531: return "HART3 состояние";
                case 532: return "HART4 состояние";
                case 533: return "HART5 состояние";
                case 534: return "HART6 состояние";
                case 535: return "HART9 состояние";
                case 536: return "HART10 состояние";
                case 537: return "HART11 состояние";
                case 538: return "HART12 состояние";
                case 539: return "HART-верс. старая";
                case 540: return "Exi-верс. старая";
                case 541: return "М33-0 Режим расчета не опред.";
                case 542: return "М33-1 Режим расчета 1";
                case 543: return "М33-2 Режим расчета 2";
                case 544: return "М33-3 Режим расчета 3";
                case 545: return "М33-4 Режим расчета 4";
                case 546: return "GBH неполный";
                case 547: return "(HFX-сбой импульса) Исчезновение сигнала подсчета импульсов измерительного канала (HFX)";
                case 548: return "(HFY-сбой импульса) Исчезновение сигнала подсчета импульсов сравнительного канала (HFY)";
                case 549: return "М33-5 DSfG-заморозка";
                case 550: return "Темп. печи >> высокая";
                case 551: return "Газ-носитель";
                case 552: return "Коэфф. срабатывания";
                case 553: return "Основа хромат.";
                case 554: return "Температура печи";
                case 555: return "Газ-носитель аммиак";
                case 556: return "Пик. хромат.";
                case 557: return "GC-сервис";
                case 558: return "Ненорм. сумма";
                case 559: return "Время удержания";
                case 560: return "Автоматич. калибровка";
                case 561: return "Работа на месте";
                case 562: return "GC6000 гексан+";
                case 563: return "GC6000 пропан";
                case 564: return "GC6000 I-бутан";
                case 565: return "GC6000 N-бутан";
                case 566: return "GC6000 нео-пентан";
                case 567: return "GC6000 I-пентан";
                case 568: return "GC6000 N-пентан";
                case 569: return "GC6000 азот";
                case 570: return "GC6000 метан";
                case 571: return "GC6000 CO2";
                case 572: return "GC6000 этан";
                case 573: return "GC6000 тепл. спос-ть";
                case 574: return "GC6000 норм. плотность";
                case 575: return "GC6000 Воббе";
                case 576: return "GC6000 коэфф. сверхсж.";
                case 577: return "GC6000 теплота сгоран.";
                case 578: return "GC6000 хар. плотности";
                case 579: return "GC6000 резерв 1";
                case 580: return "GC6000 резерв 2";
                case 581: return "GC6000 резерв 3";
                case 582: return "GC6000 связь";
                case 583: return "Fl-темп. калиб. газ 1";
                case 584: return "Fl- темп. калиб. газ 2";
                case 585: return "Fl-Drk калиб. газ 1";
                case 586: return "Fl-Drk калиб. газ 2";
                case 587: return "Fl-Drk газ-носитель";
                case 588: return "Темп. в помещ. GC";
                case 589: return "Файловая система полн.";
                case 590: return "(Qp сбой) Исчезновение сигнала расхода, пропорционального по току";
                case 591: return "Сбой калибровки";
                case 592: return "GC6000 тайм-аут";
                case 593: return "Старое показание счетч.";
                case 594: return "Новое показание счетч.";
                case 595: return "Луч 1 сбой";
                case 596: return "Луч 2 сбой";
                case 597: return "Луч 3 сбой";
                case 598: return "Луч 4 сбой";
                case 599: return "Луч 5 сбой";
                case 600: return "Луч 6 сбой";
                case 601: return "Луч 7 сбой";
                case 602: return "Луч 8 сбой";
                case 603: return "GC6000 !ошибка клибр.";
                case 604: return "T<>T-тандем";
                case 605: return "P<>P- тандем";
                case 606: return "VN<>VN- тандем";
                case 607: return "VB<>VB- тандем";
                case 608: return "DP2K отлонено";
                case 609: return "DP3K отлонено";
            }
            return "";
        }
    }
}
