//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Poll.Driver.DLMS.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Matrix.Poll.Driver.DLMS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action Implemented..
        /// </summary>
        internal static string ActionImplemented {
            get {
                return ResourceManager.GetString("ActionImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to remove selected Conformance Test results?.
        /// </summary>
        internal static string ConformanceTestRemove {
            get {
                return ResourceManager.GetString("ConformanceTestRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are going to perform conformational tests. This may take a very long time or harm your meter. Do you want to continue?.
        /// </summary>
        internal static string CTTWarning {
            get {
                return ResourceManager.GetString("CTTWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Executable files (*.dll)|*.dll|All files (*.*)|*.*.
        /// </summary>
        internal static string ExecutableFilesTxt {
            get {
                return ResourceManager.GetString("ExecutableFilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No updates available..
        /// </summary>
        internal static string ExternalMediaNoUpdates {
            get {
                return ResourceManager.GetString("ExternalMediaNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to remove selected external media?.
        /// </summary>
        internal static string ExternalMediaRemove {
            get {
                return ResourceManager.GetString("ExternalMediaRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gurux GXDLMSDirector files (*.gxc)|*.gxc|All files (*.*)|*.*.
        /// </summary>
        internal static string FilterTxt {
            get {
                return ResourceManager.GetString("FilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Help topic is associated with this item..
        /// </summary>
        internal static string HelpNotAvailable {
            get {
                return ResourceManager.GetString("HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device Manufacturer settings are not present. Do you want to install them online from Gurux Web?.
        /// </summary>
        internal static string InstallManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("InstallManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ASCII characters..
        /// </summary>
        internal static string InvalidASCII {
            get {
                return ResourceManager.GetString("InvalidASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dutations are not available..
        /// </summary>
        internal static string InvalidDurationFile {
            get {
                return ResourceManager.GetString("InvalidDurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Values are not available..
        /// </summary>
        internal static string InvalidValueFile {
            get {
                return ResourceManager.GetString("InvalidValueFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Install Manufacturer Settings first..
        /// </summary>
        internal static string ManufacturerSettingsMissing {
            get {
                return ResourceManager.GetString("ManufacturerSettingsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are open connections. Do you want to close them first?.
        /// </summary>
        internal static string OpenConnectionsTxt {
            get {
                return ResourceManager.GetString("OpenConnectionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applications updated..
        /// </summary>
        internal static string ProtocolsUpdatedTxt {
            get {
                return ResourceManager.GetString("ProtocolsUpdatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to read Association view to see all objects what the meter can offer. Do you want to do it now?.
        /// </summary>
        internal static string ReadAssociationView {
            get {
                return ResourceManager.GetString("ReadAssociationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        internal static string ReadyTxt {
            get {
                return ResourceManager.GetString("ReadyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to remove selected device(s)?.
        /// </summary>
        internal static string RemoveDeviceConfirmation {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure that you want to remove selected object?.
        /// </summary>
        internal static string RemoveObjectConfirmation {
            get {
                return ResourceManager.GetString("RemoveObjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application must be restarted to apply the changes..
        /// </summary>
        internal static string RestartTxt {
            get {
                return ResourceManager.GetString("RestartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save the changes?.
        /// </summary>
        internal static string SaveChangesTxt {
            get {
                return ResourceManager.GetString("SaveChangesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value changed.
        /// </summary>
        internal static string ValueChangedTxt {
            get {
                return ResourceManager.GetString("ValueChangedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gurux GXDLMSDirector values (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string ValuesFilterTxt {
            get {
                return ResourceManager.GetString("ValuesFilterTxt", resourceCulture);
            }
        }
    }
}
